const Constants = {
  DEFAULT_STATE: {
    session: {
      signedIn: false,
      uuid: ""
    },
    flash: {
      flashType: "",
      message: ""
    },
    books: {
      bookList: [],
      currentBook: {}
    },
    notes: {
      noteList: [],
      currentNote: {}
    }
  },
  ACTIONS: {
    REQUEST_START: "REQUEST_START",
    REQUEST_END: "REQUEST_END",
    FLASH_SUCCESS: "FLASH_SUCCESS",
    FLASH_ERROR: "FLASH_ERROR",
    FLASH_CLEAR: "FLASH_CLEAR",
    CREATE_SESSION_SUCCESS: "CREATE_SESSION_SUCCESS",
    CREATE_SESSION_FAILURE: "CREATE_SESSION_FAILURE",
    DESTROY_SESSION: "DESTROY_SESSION",
    GET_BOOKS_SUCCESS: "GET_BOOKS_SUCCESS",
    GET_BOOKS_FAILURE: "GET_BOOKS_FAILURE",
    CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
    CREATE_BOOK_FAILURE: "CREATE_BOOK_FAILURE",
    SET_CURRENT_BOOK: "SET_CURRENT_BOOK",
    CLEAR_CURRENT_BOOK: "CLEAR_CURRENT_BOOK",
    DESTROY_BOOK: "DESTROY_BOOK",
    GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
    GET_NOTES_FAILURE: "GET_NOTES_FAILURE",
    CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
    CREATE_NOTE_FAILURE: "CREATE_NOTE_FAILURE",
    UPDATE_NOTE_SUCCESS: "UPDATE_NOTE_SUCCESS",
    UPDATE_NOTE_FAILURE: "UPDATE_NOTE_FAILURE",
    SET_CURRENT_NOTE: "SET_CURRENT_NOTE",
    CLEAR_CURRENT_NOTE: "CLEAR_CURRENT_NOTE",
    DESTROY_NOTE: "DESTROY_NOTE"
  }
};

export default Constants;
